name: Linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ZKG_LIB: ./zig-cache/lib/zig/zkg

    steps:
    - name: Checkout libgit2
      uses: actions/checkout@master
      with:
        repository: libgit2/libgit2

    - name: Configure cmake
      run: cmake --configure .

    - name: Build and Install libgit2
      run: sudo cmake --build . --target install

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.5
      with:
        version: master

    - name: Compile
      run: zig build

    - name: Init
      run: ./zig-cache/bin/zkg init

    - name: Search
      run: ./zig-cache/bin/zkg search

    - name: Add
      run: ./zig-cache/bin/zkg add bearssl

    - name: Fetch
      run: ./zig-cache/bin/zkg fetch
      
    - name: Stage for Release
      run: zig build --prefix zig-cache/release
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: zkg
        path: |
          zig-cache/release/*
    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_COMPRESS: xz
        GHR_PATH: zig-cache/release/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
